#************************************************************************
#
# (C) 2004-2005
# Lehrstuhl fuer Datenbanken und Informationssysteme
# Friedrich-Schiller-Universitaet Jena
# Ernst-Abbe-Platz 1-2
# 07745 Jena
#
#************************************************************************

# Liste der zu uebersetzenden Dateien (ohne Test-Dateien!)
SOURCES := DbjLockManager.cpp 

#Liste der Testdateien
TESTS := test_client1.cpp test_client2.cpp test_start-lm.cpp test_stop-lm.cpp

#========================================================================

include ../makefile.common

