
#####################################################################
 System starten
#####################################################################

The system was started successfully. SQLSTATE=00000


#####################################################################
 Tabellen anlegen
#####################################################################

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000


8 Seg1.dbj
8 Seg2.dbj
8 Seg3.dbj
8 Seg32768.dbj
8 Seg32769.dbj
8 Seg32770.dbj
8 Seg32771.dbj
8 Seg32772.dbj
8 Seg32773.dbj
8 Seg32774.dbj
8 Seg32775.dbj
8 Seg32776.dbj
8 Seg32777.dbj
8 Seg32778.dbj
0 Seg4.dbj
0 Seg5.dbj

#####################################################################
 Daten einfuegen
#####################################################################

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000


PERSNR      VORNAME    NACHNAME             GEHALT      ADRESSE             
----------- ---------- -------------------- ----------- --------------------
          1 Klaus      Kuespert                   10000 -                   
          2 Knut       Stolze                      1500 Ernst-Abbe-Platz 2  
          3 Thomas     Mueller                     3000 Ernst-Abbe-Platz 2  
          4 Hannes     Moser                        500 Ernst-Abbe-Platz 1  

  4 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


8 Seg1.dbj
8 Seg2.dbj
8 Seg3.dbj
8 Seg32768.dbj
8 Seg32769.dbj
8 Seg32770.dbj
8 Seg32771.dbj
8 Seg32772.dbj
8 Seg32773.dbj
8 Seg32774.dbj
8 Seg32775.dbj
8 Seg32776.dbj
8 Seg32777.dbj
8 Seg32778.dbj
8 Seg4.dbj
0 Seg5.dbj

#####################################################################
 Daten loeschen
#####################################################################

The operation was completed successfully. SQLSTATE=00000


PERSNR      NACHNAME            
----------- --------------------
          1 Kuespert            
          2 Stolze              
          4 Moser               

  3 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


PERSNR      NACHNAME            
----------- --------------------
          1 Kuespert            
          2 Stolze              
          3 Mueller             
          4 Moser               

  4 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


PERSNR      NACHNAME             GEHALT     
----------- -------------------- -----------
          2 Stolze                      1500

  1 record(s) returned.

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000


  0 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


  0 record(s) returned.

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000



#####################################################################
 Delete & Rollback
#####################################################################

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000


B          
-----------
          1
          2
          3

  3 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


B          
-----------
          1
          3

  2 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


B          
-----------
          1
          2
          3

  3 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


B          
-----------
          2
          3

  2 record(s) returned.

The operation was completed successfully. SQLSTATE=00000


B          
-----------
          2
          3

  2 record(s) returned.

The operation was completed successfully. SQLSTATE=00000

The operation was completed successfully. SQLSTATE=00000



#####################################################################
 System stoppen
#####################################################################

The system was stopped successfully. SQLSTATE=00000

