#************************************************************************
#
# (C) 2004-2005
# Lehrstuhl fuer Datenbanken und Informationssysteme
# Friedrich-Schiller-Universitaet Jena
# Ernst-Abbe-Platz 1-2
# 07745 Jena
#
#************************************************************************

# Liste der zu uebersetzenden Dateien (ohne Test-Dateien!)
SOURCES := DbjIndex.cpp DbjTable.cpp DbjCatalogManager.cpp

# Liste der zu uebersetzenden Test-Dateien
TESTS := 

#========================================================================

include ../makefile.common

