
#####################################################################
 Success cases
#####################################################################

Validated access plan:
==================================================
CommitStmt
==================================================

The operation was completed successfully.


Validated access plan:
==================================================
CommitStmt
==================================================

The operation was completed successfully.



#####################################################################
 Syntax error
#####################################################################


An incomplete or invalid statement was entered.  "COMMIT garbage"



An incomplete or invalid statement was entered.  "comit"


